services:
  - docker

before_install:
  - docker build -t sunnatulloganiev/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true sunnatulloganiev/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-1"
  app: "docker-react"
  env: "Dockerreact-env"
  bucket: "elasticbeanstalk-us-east-1-802154521225"
  on:
    branch: main
  access_key_id: $AWS_ACCCESS_KEY
  secret_access_key:
    secure: "$AWS_SECRET_KEY"
